### ISSUE TITLE
outputs = self.bindings['ouputs'].data[0].tolist()  KeyError: 'ouputs'

### ISSUE THREAD

**Issue by YaoBeiji** [BaofengZan/yolov7-pose-e2e-trt#6]
self.bingdings 的keys 是：
['pre/images', '752', '797', '842', '887']
Traceback (most recent call last):
  File "trt_py_onnxpre.py", line 199, in <module>
    results, img = trt_engine.predict(img, threshold=0.5)
  File "trt_py_onnxpre.py", line 142, in predict
    outputs = self.bindings['ouputs'].data[0].tolist()
KeyError: 'ouputs'
ouputs 应该是onnx 的output_names，但是没有输出。

**Comment by YaoBeiji** [comment]
I've fixed。我用了models/export.py   应该用下面的export_onnx.py
